spring.application.name=garganoexplorer

#Legge le variabili dal file .env nella cartella principale (solo locale)
spring.config.import=optional:file:../.env[.properties]

#Database
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
